"""Dataset manifests, provenance, and the artifact catalog.

Answers one question: *exactly which immutable canonical market-data dataset
artifact is this?* — and keeps three separate answers apart while doing it.

The layering below this package is strict. Identity value objects and the
semantic encoding live in ``domain``; physical byte hashing and Parquet I/O
live in ``data``; this package composes them into manifests, registration, and
a rebuildable location index. Nothing here is imported by either layer beneath
it, and nothing here reaches for replay, execution, strategy, or UI — none of
which exist.
"""

from quant_research_terminal.catalog.comparison import (
    BarKey,
    BarKeyComparison,
    DatasetComparison,
    compare_datasets,
)
from quant_research_terminal.catalog.errors import (
    AmbiguousBarKeyError,
    ArtifactOutsideStorageRootError,
    CatalogError,
    CatalogIndexError,
    CatalogLocationConflictError,
    DatasetNotComparableError,
    InvalidSupersedesRelationError,
    LineageCycleError,
    LineageError,
    LineageIndexError,
    ManifestConflictError,
    ManifestHashMismatchError,
    MissingArtifactError,
    MissingManifestError,
    MissingRelationError,
    PhysicalArtifactHashMismatchError,
    RelationConflictError,
    RelationHashMismatchError,
    SchemaMismatchError,
    SemanticHashMismatchError,
    UnsupportedMigrationError,
)
from quant_research_terminal.catalog.index import (
    INDEX_FORMAT,
    CatalogEntry,
    CatalogIndex,
    empty_index,
    index_from_json_bytes,
)
from quant_research_terminal.catalog.lineage import (
    LINEAGE_DIRECTORY,
    LINEAGE_INDEX_FILENAME,
    LineageGraph,
    LineageIndex,
    LineageIndexEntry,
    empty_lineage_index,
    find_cycle,
    lineage_directory,
    lineage_index_path,
    load_lineage_graph,
    load_lineage_index,
    publish_supersedes_relation,
    published_relations,
    read_relation,
    rebuild_lineage_index,
    relation_from_json_bytes,
    relation_path,
    unpublished_relation_partials,
    validate_supersedes_relation,
    verify_lineage_acyclic,
    verify_lineage_index,
    write_lineage_index,
)
from quant_research_terminal.catalog.manifest import (
    MANIFEST_FORMAT,
    DatasetManifest,
    build_manifest,
    compute_manifest_hash,
    manifest_from_json_bytes,
    manifest_to_json_bytes,
)
from quant_research_terminal.catalog.migration import (
    migrate_v2_to_v3,
    normalize_symbol_mapping,
)
from quant_research_terminal.catalog.provenance import (
    DatasetOrigin,
    SourceProvenance,
    TransformationKind,
    TransformationProvenance,
    untransformed,
)
from quant_research_terminal.catalog.store import (
    RegistrationOutcome,
    VerificationOutcome,
    find_by_semantic_hash,
    load_index,
    locate_manifest,
    manifest_path,
    published_manifests,
    read_manifest,
    rebuild_index,
    register_dataset,
    resolve_location,
    verify_artifact_against_manifest,
    verify_manifest,
    verify_registration,
    write_index,
)
from quant_research_terminal.domain.dataset_lineage import (
    SUPERSEDES_FORMAT,
    RelationProvenance,
    RelationProvenanceKind,
    SupersedesRelation,
    SupersedesRelationHash,
    build_supersedes_relation,
    operator_declared,
    relation_to_json_bytes,
)

__all__ = [
    "AmbiguousBarKeyError",
    "ArtifactOutsideStorageRootError",
    "BarKey",
    "BarKeyComparison",
    "CatalogEntry",
    "CatalogError",
    "CatalogIndex",
    "CatalogIndexError",
    "CatalogLocationConflictError",
    "DatasetComparison",
    "DatasetManifest",
    "DatasetNotComparableError",
    "DatasetOrigin",
    "INDEX_FORMAT",
    "InvalidSupersedesRelationError",
    "LINEAGE_DIRECTORY",
    "LINEAGE_INDEX_FILENAME",
    "LineageCycleError",
    "LineageError",
    "LineageGraph",
    "LineageIndex",
    "LineageIndexEntry",
    "LineageIndexError",
    "MANIFEST_FORMAT",
    "ManifestConflictError",
    "ManifestHashMismatchError",
    "MissingArtifactError",
    "MissingManifestError",
    "MissingRelationError",
    "PhysicalArtifactHashMismatchError",
    "RegistrationOutcome",
    "RelationConflictError",
    "RelationHashMismatchError",
    "RelationProvenance",
    "RelationProvenanceKind",
    "SUPERSEDES_FORMAT",
    "SchemaMismatchError",
    "SemanticHashMismatchError",
    "SourceProvenance",
    "SupersedesRelation",
    "SupersedesRelationHash",
    "TransformationKind",
    "TransformationProvenance",
    "UnsupportedMigrationError",
    "VerificationOutcome",
    "build_manifest",
    "build_supersedes_relation",
    "compare_datasets",
    "compute_manifest_hash",
    "empty_index",
    "empty_lineage_index",
    "find_by_semantic_hash",
    "find_cycle",
    "index_from_json_bytes",
    "lineage_directory",
    "lineage_index_path",
    "load_index",
    "load_lineage_graph",
    "load_lineage_index",
    "locate_manifest",
    "manifest_from_json_bytes",
    "manifest_path",
    "manifest_to_json_bytes",
    "migrate_v2_to_v3",
    "normalize_symbol_mapping",
    "operator_declared",
    "publish_supersedes_relation",
    "published_manifests",
    "published_relations",
    "read_manifest",
    "read_relation",
    "rebuild_index",
    "rebuild_lineage_index",
    "register_dataset",
    "relation_from_json_bytes",
    "relation_path",
    "relation_to_json_bytes",
    "resolve_location",
    "unpublished_relation_partials",
    "untransformed",
    "validate_supersedes_relation",
    "verify_artifact_against_manifest",
    "verify_lineage_acyclic",
    "verify_lineage_index",
    "verify_manifest",
    "verify_registration",
    "write_index",
    "write_lineage_index",
]
